USE MYDB;
DROP TABLE EMPLOYEE

CREATE TABLE EMPLOYEE(
	EMPLOYEE_ID INT(10) PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(30),
    STREET_ADDRESS VARCHAR(20),
    CITY VARCHAR(20),
    STATE VARCHAR(20),
    ZIP_CODE VARCHAR(10)
);

select * from EMPLOYEE;