USE mydb;

DROP TABLE PAYMENT;
DROP TABLE CREDIT_CARD;
DROP TABLE BANK_CHECK;

CREATE TABLE PAYMENT(
	PAYMENT_ID int(10) PRIMARY KEY,
    AMOUNT double(8,2)
);

CREATE TABLE CREDIT_CARD(
	ID INT(10), 
    CARD_NUMBER VARCHAR(30),
    FOREIGN KEY(ID) references PAYMENT(PAYMENT_ID)
);

CREATE TABLE BANK_CHECK(
	ID INT(10), 
    CHECK_NUMBER VARCHAR(30),
    FOREIGN KEY(ID) references PAYMENT(PAYMENT_ID)
);

select * from PAYMENT;
select * from CREDIT_CARD;
select * from BANK_CHECK;