use mydb;

DROP TABLE CUSTOMER;
DROP TABLE PRODUCT;
DROP TABLE ORDERS;
DROP TABLE PRODUCTS_ORDERS;
DROP TABLE PRODUCTS_CUSTOMERS;

CREATE TABLE CUSTOMER(
	CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    ADDRESS_LINE1 VARCHAR(20),
    ADDRESS_LINE2 VARCHAR(20),
    CITY VARCHAR(20),
    STATE VARCHAR(20),
    ZIP VARCHAR(10)    
);

CREATE TABLE PRODUCT(
	PRODUCT_ID INT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(30) NOT NULL,
    QUANTITY_LEFT  BIGINT NOT NULL
);

CREATE TABLE ORDERS(
	ORDER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    SHIPPING_DATE DATETIME,
    DELIVERY_STATUS VARCHAR(1),
    FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE PRODUCTS_ORDERS(
	ORDER_ID INT,
	PRODUCT_ID INT,
    FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

-#CREATE TABLE PRODUCTS_CUSTOMERS(
	#PRODUCT_ID INT,
	#CUSTOMER_ID INT,    
    #FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    #FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)    
#);


select * from CUSTOMER;
select * from PRODUCT;
select * from ORDERS;
select * from PRODUCTS_ORDERS;
#select * from PRODUCTS_CUSTOMERS
