use mydb;

create table project(
	PROJECT_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
    PROJECT_NAME VARCHAR(30)
);

create table PROGRAMMER(
	PROGRAMMER_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
    PRAGRAMMER_NAME VARCHAR(30)
);

create table PROGRAMMER_PROJECT(
	PROG_ID INT(10),
    PROJ_ID INT(10),
    FOREIGN KEY(PROG_ID) REFERENCES PROGRAMMER(PROGRAMMER_ID),
    FOREIGN KEY(PROJ_ID) REFERENCES PROJECT(PROJECT_ID)
);

select * from project;
select * from PROGRAMMER;
select * from PROGRAMMER_PROJECT;

INSERT INTO project(PROJECT_NAME) VALUES("PLB");
