use mydb;

CREATE TABLE PERSON_1(
	ID INT(10) PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(40)
);

CREATE TABLE LICENSE(
	ID INT(10) PRIMARY KEY AUTO_INCREMENT,
    LICENSE_TYPE VARCHAR(10),
    PERSON_ID INT(10),
    FOREIGN KEY(PERSON_ID) REFERENCES PERSON_1(ID)
);

select * from PERSON_1;
select * from LICENSE;