use myDB;
DROP TABLE STUDENT
CREATE TABLE STUDENT(
	STUDENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    EMAIL VARCHAR(30),
    FINAL_SCORE INT(2)
);

SELECT * from STUDENT;