USE mydb;

DROP TABLE PAYMENT;
DROP TABLE CREDIT_CARD;
DROP TABLE BANK_CHECK;

CREATE TABLE CREDIT_CARD(
	PAYMENT_ID int(10) PRIMARY KEY,
    AMOUNT double(8,2),
    CARD_NUMBER VARCHAR(30)
);

CREATE TABLE BANK_CHECK(
	PAYMENT_ID int(10) PRIMARY KEY,
    AMOUNT double(8,2),
    CHECK_NUMBER VARCHAR(30)
);

select * from CREDIT_CARD;
select * from BANK_CHECK;